### ISSUE TITLE
Forebear graffle

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#316] opened 2018-04-18 18:30 UTC
- [x] Draft 
- [x] Approve
- [ ] Add polish

https://drive.google.com/drive/folders/0B8C90DSaQG_sazJtMmVHc0s3M0k

**Comment by SusanBrown** [comment] 2018-04-19 00:50
This is ready for review. We discussed it at a previous meeting and I believe what I have done reflects that discussion, and the data.

**Comment by alliyya** [comment] 2018-04-23 21:06
duplicate of #339, awaits decision on identity

**Closed by alliyya** 2018-04-23 21:06 UTC
Labels: type:duplicate
