### ISSUE TITLE
Review and Revise Preamble

### ISSUE THREAD

**Issue by JasmineDW** [cwrc/ontology#430] opened 2018-08-07 17:02 UTC
To accommodate changes to the ontology:
E.g. Spelling issues; Changes to use of Role
Review linkages to external ontologies (SEM; Deb's I&I ontology to be added)

**Comment by lemaka** [comment] 2018-09-12 19:46
@SusanBrown is this general review? If so, I can help comb over.

**Comment by alliyya** [comment] 2019-08-06 21:59
duplicate of more up to date issue #469

**Closed by alliyya** 2019-08-06 21:59 UTC
Labels: priority:routine, project:CWRC Ontology, type:documentation, type:duplicate
