### ISSUE TITLE
create CWRC primary genre subclass

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#441] opened 2018-09-19 01:00 UTC
Create subclass of http://sparql.cwrc.ca/ontologies/genre.html#genre%3ALiteraryGenre whose members will be the genres thus identified by CWRC

**Comment by alliyya** [comment] 2018-10-10 21:11
I believe this has been done? @SusanBrown

**Comment by SusanBrown** [comment] 2018-10-10 21:34
they are the same

**Comment by alliyya** [comment] 2018-10-10 21:36
Closing this issue as it's a duplicate of #428

**Closed by alliyya** 2018-10-10 21:36 UTC
Labels: type:duplicate
