### ISSUE TITLE
Uber graph

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/ontology#40] opened 2017-04-06 20:59 UTC
Create a reference graph combining our current graphs that reflects all of our decisions to date and commit to keeping it current.

**Comment by rwarren2** [comment] 2017-05-05 13:06
Pulling in @alliyya since I'd like this to be generated automatically later on.

**Comment by rwarren2** [comment] 2017-06-07 21:46
See https://drive.google.com/drive/folders/0B9lTUIf6YQsjQmhRemZQRmFrVE0 for some examples.

**Comment by alliyya** [comment] 2017-07-19 18:51
Duplicate of #48

**Closed by alliyya** 2017-07-19 18:51 UTC
Labels: Duplicate
